spring:
  application:
    name: Prosig Blog
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: prosig
    password: prosig
  flyway:
    enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
